version: "3.6"
services:

  projectname_githooks:
    container_name: projectname_githooks
    build: ./docker/images/githooks
    volumes:
      - ./.git/hooks:/tmp/.git/hooks
      - ./hooks:/tmp/hooks

  projectname_angular:
    container_name: projectname_angular
    build: ./docker/images/angular/.
#    restart: always
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
      - BUILD_COMMAND=ng build
      - SERVE_COMMAND=ng serve --host 0.0.0.0
      - APP_NAME=PROJECT-NAME
    volumes:
      - ./angular/:/home/node/angular
    tty: true

  projectname_nginx:
    container_name: projectname_nginx
    build: ./docker/images/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./angular/dist/:/usr/share/nginx/html
    tty: true
    depends_on:
      - projectname_angular
